version: '3'

services:
  mongodb_primary:
    networks:
      - ${DOCKER_NETWORK_NAME}
    image: mongo:6-jammy
    container_name: ${NAME_PRIMARY}
    restart: always
    command: ["--replSet", "${REPLICA_ID}", "--bind_ip_all", "--port", "${PORT_PRIMARY}", "--keyFile", "/data/replication_key/mongo-replication.key"]
    ports:
      - ${PORT_PRIMARY}:${PORT_PRIMARY}
    volumes:
      - volume_data_db_primary:/data/db
      - volume_data_configdb_primary:/data/configdb
      - volume_data_key_primary:/data/replication_key
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
      MONGO_INITDB_DATABASE: ${DB}
    logging:
      options:
        max-size: 10mb

  mongodb_secondary_1:
    networks:
      - ${DOCKER_NETWORK_NAME}
    image: mongo:6-jammy
    container_name: ${NAME_SECONDARY_1}
    restart: always
    command: ["--replSet", "${REPLICA_ID}", "--bind_ip_all", "--port", "${PORT_SECONDARY_1}", "--keyFile", "/data/replication_key/mongo-replication.key"]
    ports:
      - ${PORT_SECONDARY_1}:${PORT_SECONDARY_1}
    volumes:
      - volume_data_db_secondary_1:/data/db
      - volume_data_configdb_secondary_1:/data/configdb
      - volume_data_key_secondary_1:/data/replication_key
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
      MONGO_INITDB_DATABASE: ${DB}
    logging:
      options:
        max-size: 10mb

  mongodb_secondary_2:
    networks:
      - ${DOCKER_NETWORK_NAME}
    image: mongo:6-jammy
    container_name: ${NAME_SECONDARY_2}
    restart: always
    command: ["--replSet", "${REPLICA_ID}", "--bind_ip_all",  "--port", "${PORT_SECONDARY_2}", "--keyFile", "/data/replication_key/mongo-replication.key"]
    ports:
      - ${PORT_SECONDARY_2}:${PORT_SECONDARY_2}
    volumes:
      - volume_data_db_secondary_2:/data/db
      - volume_data_configdb_secondary_2:/data/configdb
      - volume_data_key_secondary_2:/data/replication_key
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
      MONGO_INITDB_DATABASE: ${DB}
    logging:
      options:
        max-size: 10mb

volumes:
  volume_data_db_primary:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/${NAME_PRIMARY}/db
  volume_data_db_secondary_1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/${NAME_SECONDARY_1}/db
  volume_data_db_secondary_2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/${NAME_SECONDARY_2}/db

  volume_data_configdb_primary:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/${NAME_PRIMARY}/configdb
  volume_data_configdb_secondary_1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/${NAME_SECONDARY_1}/configdb
  volume_data_configdb_secondary_2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/${NAME_SECONDARY_2}/configdb

  volume_data_key_primary:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/${NAME_PRIMARY}/replication_key
  volume_data_key_secondary_1:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/${NAME_SECONDARY_1}/replication_key
  volume_data_key_secondary_2:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/${NAME_SECONDARY_2}/replication_key